baseurl = "https://andypbrowne.com/"
title = "andypbrowne"

theme = "hugo-coder"

languagecode = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

[params]
    author = "Andrew Garber-Browne"
    description = "Portfolio Site"
    keywords = "blog,developer,personal"
    info = "Design code and content"

    hideCredits = false
    hideCopyright = false

    # Custom CSS
    custom_css = []

    # RTL support
    rtl = false

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xHTML = false

[taxonomies]
  description = "descriptions"
  tag = "tags"

[[menu.main]]
    name = "About"
    weight = 1
    url = "/about/"
[[menu.main]]
    name = "Work"
    weight = 2
    url  = "/"
[[menu.main]]
    name = "Words"
    weight = 3
    url  = "/posts/"

